---
name: Push to LuaRocks

on:
  push:
    tags:
      - '*'
  release:
    types:
      - created
  pull_request:
  workflow_dispatch:

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to count the commits
      - name: Get Version
        run: echo "LUAROCKS_VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: Luarocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: ${{ env.LUAROCKS_VERSION }}
          dependencies: |
            lua == 5.1
          license: GPL-2+
          detailed_description: |
            It is intended to be used

              - by users or plugin managers that don't provide a convenient API for lazy-loading.
              - by plugin managers, to provide a convenient API for lazy-loading.
